export { default as Info } from './info';
export { default as SendPage } from './sendPage';
export { default as HomePage } from './homePage'
export { default as ChooseMethod } from './chooseMethod'
export { default as NavFooter } from './navFooter'
export { default as Footer } from './footer'
export { default as BalancePage } from './balancePage'
export { default as BalanceCard } from './balanceCard'
export { default as ConfirmationPage } from './confirmationPage'